[package]
name = "SolarBuster"
version = "0.1.0"
edition = "2024"

[dependencies]


arg = "0.4.1"
clap = { version = "4.5.58", features = ["derive"] }
colored = "3.1.1"
reqwest = { version = "0.12", features = ["json"] }
tokio = { version = "1", features = ["full"] }
